export const plants = [
  {
    category: "indoor",
    image: "Arum",
    heading: "Arum Lily",
    subHeading: "Flower",
    description: "This is a flower",
    sun: "Full sun",
    water: "Weekly",
    feed: "Bi-weekly",
    imageUrl: "http://localhost:3000/public/arum_lily.jpeg",
  },
  {
    category: "indoor",
    image: "Arum",
    heading: "Arum Lily",
    subHeading: "Flower",
    description: "This is a flower",
    sun: "Full sun",
    water: "Weekly",
    feed: "Bi-weekly",
  },
  {
    category: "outdoor",
    image: "Arum",
    heading: "Arum Lily",
    subHeading: "Flower",
    description: "This is a flower",
    sun: "Full sun",
    water: "Weekly",
    feed: "Bi-weekly",
  },
  {
    category: "outdoor",
    image: "Arum",
    heading: "Arum Lily",
    subHeading: "Flower",
    description: "This is a flower",
    sun: "Full sun",
    water: "Weekly",
    feed: "Bi-weekly",
  },
];
